PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX text: <http://jena.apache.org/text#>
PREFIX imgt: <https://www.imgt.org/imgt-ontology#>
PREFIX faldo: <http://biohackathon.org/resource/faldo#>
PREFIX so: <http://purl.obolibrary.org/obo/so#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT  ?struct_id ?Structure ?article_title  ?article ?article_date  ?epitope

WHERE{
  ?seq imgt:isCrystalOf ?struct ;
       imgt:hasBibliographicReference ?article .
  ?article dc:title ?article_title; 
           dc:date ?article_date;
           imgt:has_journal ?article_journal .

      ?struct imgt:immune_epitope ?epitope ; 
              rdfs:label ?struct_id;
              imgt:common_name ?Structure .
  
} limit 50
